repos:

  - repo: local

    hooks:

      - id: pytest

        name: Run pytest

        entry: pytest tests -v

        language: python

        pass_filenames: false



  - repo: https://github.com/psf/black

    rev: 24.10.0

    hooks:

      - id: black

        name: Run Black

        language: python

        args: [--verbose, src/, tests/, setup.py]

        stages: [pre-commit]

        additional_dependencies: []

        require_serial: true

        pass_filenames: false
